spring:
  cloud:
    stream:
      function:
        definition: generate;process;consume
      bindings:
        generate-out-0:
          destination: destination1
          group: g1
        process-in-0:
          destination: destination1
          group: g1
        process-out-0:
          destination: destination2
          group: g2
        consume-in-0:
          destination: destination2
          group: g2
        bindingServiceProperties:
          defaultBinder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: localhost
#                port: 5672
#                username: guest
#                password: guest
#                virtual-host: /
    rabbitmq:
      host: localhost
      port: 5672
      username: admin
      password: admin
      virtual-host: /